version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore packages
          working_directory: ~/project/src/DotNetCoreHelloFromAppSettings
          command: dotnet restore
      - run:
          name: Build App
          working_directory: ~/project/src/DotNetCoreHelloFromAppSettings
          command: dotnet build
      - run:
          name: Run App
          working_directory: ~/project/src/DotNetCoreHelloFromAppSettings
          command: dotnet run
      - run:
          name: Run Unit Tests
          working_directory: ~/project/src/UnitTestProject
          command: dotnet test
