version: 2.0
jobs:
  build-app:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore packages
          working_directory: ~/project/src/DotNetCoreHelloFromAppSettings
          command: dotnet restore
      - run:
          name: Build App
          working_directory: ~/project/src/DotNetCoreHelloFromAppSettings
          command: dotnet build
      - run:
          name: Run App
          working_directory: ~/project/src/DotNetCoreHelloFromAppSettings
          background: true
          command: dotnet run
      - run:
          name: Run Unit Tests
          working_directory: ~/project/src/UnitTestProject
          command: dotnet test
      - persist_to_workspace:
              root: .
              paths:
                - Dockerfile
                - reconfiguration_script.sh
                - src/DotNetCoreHelloFromAppSettings/bin/Debug/netcoreapp2.0/DotNetCoreHelloFromAppSettings.dll
  build-image:
    environment:
      IMAGE_NAME: zeitler/circleci-ci-sample
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build-app
      - build-image:
          context: dockerhub
          requires:
            - build-app
#      - push-image:
#          requires:
#            - build-image
